//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCibertecCafe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIBER_COFFEEEntities : DbContext
    {
        public CIBER_COFFEEEntities()
            : base("name=CIBER_COFFEEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT_REQUEST> CLIENT_REQUEST { get; set; }
        public virtual DbSet<PRODUCT_LETTER> PRODUCT_LETTER { get; set; }
        public virtual DbSet<SALE_DETAIL> SALE_DETAIL { get; set; }
    }
}
