//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCibertecCafe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CLIENT_REQUEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT_REQUEST()
        {
            this.SALE_DETAIL = new HashSet<SALE_DETAIL>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "El campo nombre es obligatorio.")]
        [Display(Name = "Nombres")]
        public string NAMES { get; set; }

        [Required(ErrorMessage = "El campo apellido es obligatorio.")]
        [Display(Name = "Apellidos")]
        public string SURNAMES { get; set; }

        [Required(ErrorMessage = "El campo correo es obligatorio.")]
        [Display(Name = "Correo")]
        [EmailAddress]
        public string MAIL { get; set; }

        [Required(ErrorMessage = "El campo teléfono es obligatorio.")]
        [Display(Name = "Teléfono")]
        [RegularExpression(@"^(\d{9})$", ErrorMessage = "Número de teléfono debe contener 9 digitos.")]
        [Phone(ErrorMessage = "Formato no válido de teléfono")]
        public string TEL_NUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_DETAIL> SALE_DETAIL { get; set; }
    }
}
