//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCibertecCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_DETAIL
    {
        public int ID_CLIENT { get; set; }
        public int ID_PRODUCT { get; set; }
        public int QUANTITY_PRODUCT { get; set; }
        public decimal TOTAL { get; set; }
        public decimal TOTAL_SALE { get; set; }
        public int ID { get; set; }
    
        public virtual CLIENT_REQUEST CLIENT_REQUEST { get; set; }
        public virtual PRODUCT_LETTER PRODUCT_LETTER { get; set; }
    }
}
